<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>
  <ItemGroup><Compile Include="Program.cs" /><Compile Include="ArtsTests.cs" /><Compile Include="SkillsTests.cs" /><Compile Include="EquipmentTests.cs" /><Compile Include="EquipmentSwitchTests.cs" /><Compile Include="GemTests.cs" /></ItemGroup>
  <ItemGroup><ProjectReference Include="../core/Core.csproj" /></ItemGroup>
  <ItemGroup><Compile Include="InventoryTests.cs" /><Compile Include="AchievementTests.cs" /></ItemGroup>
  <ItemGroup><Compile Include="SkillLinksTests.cs" /></ItemGroup>
</Project>
