<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="GuiProgram.cs" />
    <Compile Include="EquipmentTests.cs" />
    <ProjectReference Include="../gui/XbdeEditor.Gui.csproj" />
    <PackageReference Include="Avalonia.Headless" Version="12.1.3" />
  </ItemGroup>
</Project>
