<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>XbdeEditor.Cli</AssemblyName>
    <JsonSerializerIsReflectionEnabledByDefault>true</JsonSerializerIsReflectionEnabledByDefault>
    <BuiltInComInteropSupport>false</BuiltInComInteropSupport>
  </PropertyGroup>
  <ItemGroup><ProjectReference Include="../core/Core.csproj" /></ItemGroup>
</Project>
