<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>XbdeEditor.Core</AssemblyName>
    <RootNamespace>XbdeEditor.Core</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="Data/achievements.tsv" />
    <EmbeddedResource Include="Data/inventory.tsv" />
    <EmbeddedResource Include="Data/arts.tsv" />
    <EmbeddedResource Include="Data/skills.tsv" />
    <EmbeddedResource Include="Data/skill-trees.tsv" />
    <EmbeddedResource Include="Data/skill-link-shapes.tsv" />
    <EmbeddedResource Include="Data/equipment.tsv" />
    <EmbeddedResource Include="Data/equipment-rules.tsv" />
    <EmbeddedResource Include="Data/gem-effects.tsv" />
    <EmbeddedResource Include="Data/gem-rules.tsv" />
  </ItemGroup>
</Project>
