<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>XbdeEditor.Core</AssemblyName>
    <RootNamespace>XbdeEditor.Core</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="Data/arts.tsv" />
    <EmbeddedResource Include="Data/skills.tsv" />
    <EmbeddedResource Include="Data/skill-trees.tsv" />
  </ItemGroup>
</Project>
